server:
  port: 9000
spring:
  application:
    name: "@pom.artifactId@"
  datasource:
    url: jdbc:mysql://localhost:3306/mzzb_disc_shelfs_dev?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: fuhaiwei
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
      hibernate.format_sql: true
    show-sql: true
  activemq:
    broker-url: tcp://localhost:61616
    password: ${activemq.password}
    user: admin

---
spring:
  profiles: pro
  datasource:
    url: jdbc:mysql://localhost:3306/mzzb_disc_shelfs_pro?useUnicode=true&characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: false
